[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ruminations"
authors = [{name = "Alex Heinrich", email = "atheinrich@outlook.com"}]
dynamic = ["version", "description"]
